### ISSUE TITLE
Automated Test Suite doesn't work

### ISSUE THREAD

**Issue by 123Giavonni** [LordNed/WindEditor#21]
I set up the correct directories, and the output directory even contains the correct folders (A_mori.wrkDir/Room0 or /Stage) but I don't see dzr, dzs, bdl, arc, or any files like those. This might be a bit late.

**Comment by LordNed** [comment]
What exactly were you trying to test with it? I recall writing it as a way to rapidly open and close all of the files and run a check against fields during file loading. You'd probably need to edit the source code to make it do anything useful if it even still works, I don't remember if I supported it past the initial testing I did before deciding that the fields we had verified were indeed padding. It was mostly built as a tool to check that our assumptions were right across a wide range of files.

**Comment by 123Giavonni** [comment]
It's fine, I was just wondering if there was a simple fix.

**Comment by LordNed** [comment]
I'm not sure you're using it for it's intended purpose. What do you expect it to do?
